let
  # Public root certificate generated by the persistent Webshop Compose Caddy
  # data volume. Never add Caddy's private key to this repository.
  webshopCaddyRoot = ''
    -----BEGIN CERTIFICATE-----
    MIIBpDCCAUqgAwIBAgIRAPVuF6M89GE57woq7xhHhMkwCgYIKoZIzj0EAwIwMDEu
    MCwGA1UEAxMlQ2FkZHkgTG9jYWwgQXV0aG9yaXR5IC0gMjAyNiBFQ0MgUm9vdDAe
    Fw0yNjA3MTQwNjQxNTVaFw0zNjA1MjIwNjQxNTVaMDAxLjAsBgNVBAMTJUNhZGR5
    IExvY2FsIEF1dGhvcml0eSAtIDIwMjYgRUNDIFJvb3QwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAAQ7wye1ZybZhoPmrmm9Qx2yLu61UCrd57VHNySI7v47Oztn4/0E
    k35iDOxwVGDz7utPocfT8wGF6XIAzAeGy0wso0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUk/UeMo7D6NbDFM2I0GvtxCnB
    a8owCgYIKoZIzj0EAwIDSAAwRQIhAM3qT32aS1a+3i6P1EUX2vOhfoh8+mxbWgWf
    vH3scEP4AiBZKpBAseMEPzP6TGhcKfB99E2+L5G/6RqR9aC/1qLX+w==
    -----END CERTIFICATE-----
  '';
in
{
  # Android Emulator needs host KVM access. The work host already gets this via
  # virt-manager, but keep it here as part of the SIGA Android emulator feature.
  users.users.luiz.extraGroups = [ "kvm" ];

  services.dnsmasq = {
    enable = true;
    settings = {
      listen-address = [ "127.0.0.1" ];
      bind-interfaces = true;
      no-hosts = true;
      no-resolv = true;
      server = [
        "1.1.1.1"
        "8.8.8.8"
      ];
      address = [
        "/roi.local/10.0.2.2"
        "/siga-webshop.local/10.0.2.2"
      ];
    };
  };

  # NixOS Firefox uses the system p11-kit trust source generated from
  # security.pki, so this also fixes browser trust for the local Webshop.
  security.pki.certificates = [ webshopCaddyRoot ];

  environment.etc."android-siga/caddy-local-root.crt" = {
    text = webshopCaddyRoot;
    mode = "0644";
  };
}
